### ISSUE TITLE
Automatic course subscription

### ISSUE THREAD

**Issue by dasistwas** [winnidat/moodlemobile2#5]
Every new user has to be automatically subscribed to specific courses. To achieve that, we have to use autoenrol plugin:

Possible plugins to use:
https://moodle.org/plugins/enrol_autoenrol (last version for M2.8)
https://moodle.org/plugins/enrol_auto (last version for M3.0)

Although there aren't new version for recent Moodle releases, the plugins could work properly. Testing needed.

**Comment by winnidat** [comment]
https://moodle.org/plugins/enrol_auto only working in Browser (Moodle 3.3) 
Possible solution: Observe other events in plugin db/events.php

**Comment by winnidat** [comment]
Sadly Mobile Web Service does not trigger events like user_loggedin. 
enrol_self_enrol_user might work.
https://docs.moodle.org/dev/Web_service_API_functions

Added Handler for event user_created to enrol_auto https://github.com/winnidat/moodle-enrol_auto

**Comment by dasistwas** [comment]
We do not need this event. The event we need is user_created.
